version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    env_file:
      - ./.envs/.local/.nginx
    volumes:
      - "./app:/usr/share/nginx/html:ro"
    ports:
      - "80:80"