version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
      image: ${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_NAME }}:${GITHUB_REF:11}
    volumes:
      - "./app:/usr/share/nginx/html:ro"
    ports:
      - "80:80"