version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: baikovdev/nginx-test
    volumes:
      - "./app:/usr/share/nginx/html:ro"
    ports:
      - "80:80"