name: Publish on Docker Hub and Deploy

on:
  push:
    branches:
      - dev

jobs:
  test_status:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Build the Stack
        run:  docker-compose -f local.yml build

      - name: Run the Stack
        run:  docker-compose -f local.yml up -d
      
      - name: Check http status code of production site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["http://127.0.0.1",]'
          expected: '[200]'

      - name: Tear down the Stack
        run:  docker-compose -f local.yml down
